export const PermissionsConstants = {
    GET_PERMISSIONS_SUCCESS: 'GET_PERMISSIONS_SUCCESS',
    GET_PERMISSIONS_REQUEST: 'GET_PERMISSIONS_REQUEST',

    PUT_PERMISSIONS_SUCCESS: 'PUT_PERMISSIONS_SUCCESS',
    PUT_PERMISSIONS_FAIL: 'PUT_PERMISSIONS_FAIL',
    PUT_PERMISSIONS_REQUEST: 'PUT_PERMISSIONS_REQUEST'
}