export const UserConstants = {
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',

    ADD_USER: 'ADD_USER',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',

    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_REQUEST: 'GET_USER_REQUEST',

    PUT_PASSWORD_SUCCESS: 'PUT_PASSWORD_SUCCESS',
    PUT_PASSWORD_FAIL: 'PUT_PASSWORD_FAIL',

    FIND_USER_SUCCESS: 'FIND_USER_SUCCESS',

    CLEAR_VALIDATION: 'CLEAR_VALIDATION'

}