export const FileConstants = {
    GET_FILE_SUCCESS: 'GET_FILE_SUCCESS',
    GET_FILE_FAIL: 'GET_FILE_FAIL',

    POST_FILE_SUCCESS: 'POST_FILE_SUCCESS',
    POST_FILE_FAIL: 'POST_FILE_FAIL',
    POST_FILE_REQUEST: 'POST_FILE_REQUEST',

    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAIL: 'DELETE_FILE_FAIL',

    TOGGLE_ADD_FILE: 'TOGGLE_ADD_FILE',
    TOGGLE_DELETE_FILE: 'TOGGLE_DELETE_FILE'
}