export const FileConstants = {
    GET_FILE_SUCCESS: 'GET_FILE_SUCCESS',
    GET_FILE_FAIL: 'GET_FILE_FAIL',

    POST_FILE_SUCCESS: 'POST_FILE_SUCCESS',
    POST_FILE_FAIL: 'POST_FILE_FAIL',
    POST_FILE_REQUEST: 'POST_FILE_REQUEST'
}