export const LoginConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_FETCH: 'LOGIN_FETCH',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST'
}