export const LogsConstants = {
    GET_LOGS_SUCCESS: 'GET_LOGS_SUCCESS',
    GET_LOGS_REQUEST: 'GET_LOGS_REQUEST',

    GET_LOG_SUCCESS: 'GET_LOG_SUCCESS',
    GET_LOG_FAIL: 'GET_LOG_FAIL',
    GET_LOG_REQUEST: 'GET_LOG_REQUEST'
}