export const OrdersConstants = {
    GET_ORDERS_SUCCCESS: 'GET_ORDERS_SUCCCESS',
    GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
    GET_ORDERS_FAIL: 'GET_ORDERS_FAIL',

    FIND_ORDERS_SUCCESS: 'FIND_ORDERS_SUCCESS',
    FIND_ORDERS_FAIL: 'FIND_ORDERS_FAIL',
    FIND_ORDERS_REQUEST: 'FIND_ORDERS_REQUEST',

    FIND_ORDER_SUCCESS: 'FIND_ORDER_SUCCESS',
    FIND_ORDER_FAIL: 'FIND_ORDER_FAIL',
    FIND_ORDER_REQUEST: 'FIND_ORDER_REQUEST',

    POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
    POST_ORDER_FAIL: 'POST_ORDER_FAIL',
    POST_ORDER_REQUEST: 'POST_ORDER_REQUEST'
}