export const RegisterConstants = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_REQUEST: 'REGISTER_REQUEST',

    CLEAR_REGISTER_VALIDATION: 'CLEAR_REGISTER_VALIDATION'
}