export const UserConstants = {
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAIL: 'GET_USERS_FAIL',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',

    ADD_USER: 'ADD_USER',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST'

}